version: "3"
services:
  hello-world:
    build: ../containers/haskell
    volumes:
      - stack-root:/stack-root
      - .:/Users/camerongera/Projects/meet-ups/Feb2018/hello-haskell
    working_dir: /Users/camerongera/Projects/meet-ups/Feb2018/hello-haskell
    command: ["stack", "build", "--fast", "--exec", "hello-haskell-exe"]
    tty: true

# Note: these volume definitions are duplicated in
# the docker-compose.local.yml for convenience. Sharing
# definitions in a common file is more cumbersome than
# managing the duplication right now.
volumes:
  stack-root:
